function species_to_dex(name){
switch (name) {
	case "Bulbasaur":
		return "001";
	case "Ivysaur":
		return "002";
	case "Venusaur":
		return "003";
	case "Chikorita":
		return "152";
	case "Bayleef":
		return "153";
	case "Meganium":
		return "154";
	case "Treecko":
		return "252";
	case "Grovyle":
		return "253";
	case "Sceptile":
		return "254";
	case "Turtwig":
		return "387";
	case "Grotle":
		return "388";
	case "Torterra":
		return "389";
	case "Snivy":
		return "495";
	case "Servine":
		return "496";
	case "Serperior":
		return "497";
	case "Chespin":
		return "650";
	case "Quilladin":
		return "651";
	case "Chesnaught":
		return "652";
	case "Charmander":
		return "004";
	case "Charmeleon":
		return "005";
	case "Charizard":
		return "006";
	case "Cyndaquil":
		return "155";
	case "Quilava":
		return "156";
	case "Typhlosion":
		return "157";
	case "Torchic":
		return "255";
	case "Combusken":
		return "256";
	case "Blaziken":
		return "257";
	case "Chimchar":
		return "390";
	case "Monferno":
		return "391";
	case "Infernape":
		return "392";
	case "Tepig":
		return "498";
	case "Pignite":
		return "499";
	case "Emboar":
		return "500";
	case "Fennekin":
		return "653";
	case "Braixen":
		return "654";
	case "Delphox":
		return "655";
	case "Squirtle":
		return "007";
	case "Wartortle":
		return "008";
	case "Blastoise":
		return "009";
	case "Totodile":
		return "158";
	case "Croconaw":
		return "159";
	case "Feraligatr":
		return "160";
	case "Mudkip":
		return "258";
	case "Marshtomp":
		return "259";
	case "Swampert":
		return "260";
	case "Piplup":
		return "393";
	case "Prinplup":
		return "394";
	case "Empoleon":
		return "395";
	case "Oshawott":
		return "501";
	case "Dewott":
		return "502";
	case "Samurott":
		return "503";
	case "Froakie":
		return "656";
	case "Frogadier":
		return "657";
	case "Greninja":
		return "658";
	case "Caterpie":
		return "010";
	case "Metapod":
		return "011";
	case "Butterfree":
		return "012";
	case "Weedle":
		return "013";
	case "Kakuna":
		return "014";
	case "Beedrill":
		return "015";
	case "Sewaddle":
		return "540";
	case "Swadloon":
		return "541";
	case "Leavanny":
		return "542";
	case "Venipede":
		return "543";
	case "Whirlipede":
		return "544";
	case "Scolipede":
		return "545";
	case "Wurmple":
		return "265";
	case "Silcoon":
		return "266";
	case "Beautifly":
		return "267";
	case "Cascoon":
		return "268";
	case "Dustox":
		return "269";
	case "Scatterbug":
		return "664";
	case "Spewpa":
		return "665";
	case "Vivillon":
		return "666";
	case "Pidgey":
		return "016";
	case "Pidgeotto":
		return "017";
	case "Pidgeot":
		return "018";
	case "Starly":
		return "396";
	case "Staravia":
		return "397";
	case "Staraptor":
		return "398";
	case "Pidove":
		return "519";
	case "Tranquill":
		return "520";
	case "Unfezant":
		return "521";
	case "Fletchling":
		return "661";
	case "Fletchinder":
		return "662";
	case "Talonflame":
		return "663";
	case "Nidoran F":
		return "029";
	case "Nidorina":
		return "030";
	case "Nidoqueen":
		return "031";
	case "Nidoran M":
		return "032";
	case "Nidorino":
		return "033";
	case "Nidoking":
		return "034";
	case "Zubat":
		return "041";
	case "Golbat":
		return "042";
	case "Crobat":
		return "169";
	case "Igglybuff":
		return "174";
	case "Jigglypuff":
		return "039";
	case "Wigglytuff":
		return "040";
	case "Happiny":
		return "440";
	case "Chansey":
		return "113";
	case "Blissey":
		return "242";
	case "Whismur":
		return "293";
	case "Loudred":
		return "294";
	case "Exploud":
		return "295";
	case "Lillipup":
		return "506";
	case "Herdier":
		return "507";
	case "Stoutland":
		return "508";
	case "Porygon":
		return "137";
	case "Porygon2":
		return "233";
	case "Porygon-Z":
		return "474";
	case "Slakoth":
		return "287";
	case "Vigoroth":
		return "288";
	case "Slaking":
		return "289";
	case "Oddish":
		return "043";
	case "Gloom":
		return "044";
	case "Vileplume":
		return "045";
	case "Bellossom":
		return "182";
	case "Bellsprout":
		return "069";
	case "Weepinbell":
		return "070";
	case "Victreebel":
		return "071";
	case "Hoppip":
		return "187";
	case "Skiploom":
		return "188";
	case "Jumpluff":
		return "189";
	case "Lotad":
		return "270";
	case "Lombre":
		return "271";
	case "Ludicolo":
		return "272";
	case "Seedot":
		return "273";
	case "Nuzleaf":
		return "274";
	case "Shiftry":
		return "275";
	case "Budew":
		return "406";
	case "Roselia":
		return "315";
	case "Roserade":
		return "407";
	case "Pichu":
		return "172";
	case "Pikachu":
		return "025";
	case "Raichu":
		return "026";
	case "Magnemite":
		return "081";
	case "Magneton":
		return "082";
	case "Magnezone":
		return "462";
	case "Mareep":
		return "179";
	case "Flaaffy":
		return "180";
	case "Ampharos":
		return "181";
	case "Shinx":
		return "403";
	case "Luxio":
		return "404";
	case "Luxray":
		return "405";
	case "Tynamo":
		return "602";
	case "Eelektrik":
		return "603";
	case "Eelektross":
		return "604";
	case "Elekid":
		return "239";
	case "Electabuzz":
		return "125";
	case "Electivire":
		return "466";
	case "Magby":
		return "240";
	case "Magmar":
		return "126";
	case "Magmortar":
		return "467";
	case "Poliwag":
		return "060";
	case "Poliwhirl":
		return "061";
	case "Poliwrath":
		return "062";
	case "Politoed":
		return "186";
	case "Azurill":
		return "298";
	case "Marill":
		return "183";
	case "Azumarill":
		return "184";
	case "Tympole":
		return "535";
	case "Palpitoad":
		return "536";
	case "Seismitoad":
		return "537";
	case "Horsea":
		return "116";
	case "Seadra":
		return "117";
	case "Kingdra":
		return "230";
	case "Spheal":
		return "363";
	case "Sealeo":
		return "364";
	case "Walrein":
		return "365";
	case "Vanillite":
		return "582";
	case "Vanillish":
		return "583";
	case "Vanilluxe":
		return "584";
	case "Ralts":
		return "280";
	case "Kirlia":
		return "281";
	case "Gardevoir":
		return "282";
	case "Gallade":
		return "475";
	case "Abra":
		return "063";
	case "Kadabra":
		return "064";
	case "Alakazam":
		return "065";
	case "Gothita":
		return "574";
	case "Gothorita":
		return "575";
	case "Gothitelle":
		return "576";
	case "Solosis":
		return "577";
	case "Duosion":
		return "578";
	case "Reuniclus":
		return "579";
	case "Machop":
		return "066";
	case "Machoke":
		return "067";
	case "Machamp":
		return "068";
	case "Timburr":
		return "532";
	case "Gurdurr":
		return "533";
	case "Conkeldurr":
		return "534";
	case "Geodude":
		return "074";
	case "Graveler":
		return "075";
	case "Golem":
		return "076";
	case "Roggenrola":
		return "524";
	case "Boldore":
		return "525";
	case "Gigalith":
		return "526";
	case "Rhyhorn":
		return "111";
	case "Rhydon":
		return "112";
	case "Rhyperior":
		return "464";
	case "Swinub":
		return "220";
	case "Piloswine":
		return "221";
	case "Mamoswine":
		return "473";
	case "Sandile":
		return "551";
	case "Krokorok":
		return "552";
	case "Krookodile":
		return "553";
	case "Aron":
		return "304";
	case "Lairon":
		return "305";
	case "Aggron":
		return "306";
	case "Klink":
		return "599";
	case "Klang":
		return "600";
	case "Klinklang":
		return "601";
	case "Honedge":
		return "679";
	case "Doublade":
		return "680";
	case "Aegislash":
		return "681";
	case "Gastly":
		return "092";
	case "Haunter":
		return "093";
	case "Gengar":
		return "094";
	case "Duskull":
		return "355";
	case "Dusclops":
		return "356";
	case "Dusknoir":
		return "477";
	case "Litwick":
		return "607";
	case "Lampent":
		return "608";
	case "Chandelure":
		return "609";
	case "Cleffa":
		return "173";
	case "Clefairy":
		return "035";
	case "Clefable":
		return "036";
	case "Togepi":
		return "175";
	case "Togetic":
		return "176";
	case "Togekiss":
		return "468";
	case "FlabÉBÉ":
		return "669";
	case "Floette":
		return "670";
	case "Florges":
		return "671";
	case "Trapinch":
		return "328";
	case "Vibrava":
		return "329";
	case "Flygon":
		return "330";
	case "Axew":
		return "610";
	case "Fraxure":
		return "611";
	case "Haxorus":
		return "612";
	case "Rattata":
		return "019";
	case "Raticate":
		return "020";
	case "Sentret":
		return "161";
	case "Furret":
		return "162";
	case "Zigzagoon":
		return "263";
	case "Linoone":
		return "264";
	case "Bidoof":
		return "399";
	case "Bibarel":
		return "400";
	case "Patrat":
		return "504";
	case "Watchog":
		return "505";
	case "Bunnelby":
		return "659";
	case "Diggersby":
		return "660";
	case "Meowth":
		return "052";
	case "Persian":
		return "053";
	case "Skitty":
		return "300";
	case "Delcatty":
		return "301";
	case "Glameow":
		return "431";
	case "Purugly":
		return "432";
	case "Minccino":
		return "572";
	case "Cinccino":
		return "573";
	case "Buneary":
		return "427";
	case "Lopunny":
		return "428";
	case "Snubbull":
		return "209";
	case "Granbull":
		return "210";
	case "Aipom":
		return "190";
	case "Ambipom":
		return "424";
	case "Deerling":
		return "585";
	case "Sawsbuck":
		return "586";
	case "Teddiursa":
		return "216";
	case "Ursaring":
		return "217";
	case "Lickitung":
		return "108";
	case "Lickilicky":
		return "463";
	case "Munchlax":
		return "446";
	case "Snorlax":
		return "143";
	case "Burmy":
		return "412";
	case "Wormadam P":
	case "Wormadam (P)":
	case "Wormadam-P":
	case "Wormadam Plant":
	case "Wormadam (Plant)":
	case "Wormadam-Plant":
		return "413";
	case "Wormadam S":
	case "Wormadam (S)":
	case "Wormadam-S":
	case "Wormadam Sand":
	case "Wormadam (Sand)":
	case "Wormadam-Sand":
		return "413:S";
	case "Wormadam T":
	case "Wormadam (T)":
	case "Wormadam-T":
	case "Wormadam Trash":
	case "Wormadam (Trash)":
	case "Wormadam-Trash":
		return "413:S";
	case "Mothim":
		return "414";
	case "Nincada":
		return "290";
	case "Ninjask":
		return "291";
	case "Shedinja":
		return "292";
	case "Paras":
		return "046";
	case "Parasect":
		return "047";
	case "Venonat":
		return "048";
	case "Venomoth":
		return "049";
	case "Ledyba":
		return "165";
	case "Ledian":
		return "166";
	case "Spinarak":
		return "167";
	case "Ariados":
		return "168";
	case "Yanma":
		return "193";
	case "Yanmega":
		return "469";
	case "Pineco":
		return "204";
	case "Forretress":
		return "205";
	case "Surskit":
		return "283";
	case "Masquerain":
		return "284";
	case "Kricketot":
		return "401";
	case "Kricketune":
		return "402";
	case "Combee":
		return "415";
	case "Vespiquen":
		return "416";
	case "Dwebble":
		return "557";
	case "Crustle":
		return "558";
	case "Karrablast":
		return "588";
	case "Escavalier":
		return "589";
	case "Shelmet":
		return "616";
	case "Accelgor":
		return "617";
	case "Joltik":
		return "595";
	case "Galvantula":
		return "596";
	case "Scyther":
		return "123";
	case "Scizor":
		return "212";
	case "Larvesta":
		return "636";
	case "Volcarona":
		return "637";
	case "Spearow":
		return "021";
	case "Fearow":
		return "022";
	case "Doduo":
		return "084";
	case "Dodrio":
		return "085";
	case "Hoothoot":
		return "163";
	case "Noctowl":
		return "164";
	case "Taillow":
		return "276";
	case "Swellow":
		return "277";
	case "Rufflet":
		return "627";
	case "Braviary":
		return "628";
	case "Swablu":
		return "333";
	case "Altaria":
		return "334";
	case "Noibat":
		return "714";
	case "Noivern":
		return "715";
	case "Ekans":
		return "023";
	case "Arbok":
		return "024";
	case "Stunky":
		return "434";
	case "Skuntank":
		return "435";
	case "Grimer":
		return "088";
	case "Muk":
		return "089";
	case "Koffing":
		return "109";
	case "Weezing":
		return "110";
	case "Gulpin":
		return "316";
	case "Swalot":
		return "317";
	case "Trubbish":
		return "568";
	case "Garbodor":
		return "569";
	case "Skorupi":
		return "451";
	case "Drapion":
		return "452";
	case "Croagunk":
		return "453";
	case "Toxicroak":
		return "454";
	case "Skrelp":
		return "690";
	case "Dragalge":
		return "691";
	case "Sandshrew":
		return "027";
	case "Sandslash":
		return "028";
	case "Diglett":
		return "050";
	case "Dugtrio":
		return "051";
	case "Cubone":
		return "104";
	case "Marowak":
		return "105";
	case "Gligar":
		return "207";
	case "Gliscor":
		return "472";
	case "Phanpy":
		return "231";
	case "Donphan":
		return "232";
	case "Baltoy":
		return "343";
	case "Claydol":
		return "344";
	case "Hippopotas":
		return "449";
	case "Hippowdon":
		return "450";
	case "Drilbur":
		return "529";
	case "Excadrill":
		return "530";
	case "Golett":
		return "622";
	case "Golurk":
		return "623";
	case "Bonsly":
		return "438";
	case "Sudowoodo":
		return "185";
	case "Nosepass":
		return "299";
	case "Probopass":
		return "476";
	case "Onix":
		return "095";
	case "Steelix":
		return "208";
	case "Binacle":
		return "688";
	case "Barbaracle":
		return "689";
	case "Bronzor":
		return "436";
	case "Bronzong":
		return "437";
	case "Sunkern":
		return "191";
	case "Sunflora":
		return "192";
	case "Tangela":
		return "114";
	case "Tangrowth":
		return "465";
	case "Cherubi":
		return "420";
	case "Cherrim":
		return "421";
	case "Cottonee":
		return "546";
	case "Whimsicott":
		return "547";
	case "Petilil":
		return "548";
	case "Lilligant":
		return "549";
	case "Foongus":
		return "590";
	case "Amoonguss":
		return "591";
	case "Shroomish":
		return "285";
	case "Breloom":
		return "286";
	case "Ferroseed":
		return "597";
	case "Ferrothorn":
		return "598";
	case "Cacnea":
		return "331";
	case "Cacturne":
		return "332";
	case "Exeggcute":
		return "102";
	case "Exeggutor":
		return "103";
	case "Snover":
		return "459";
	case "Abomasnow":
		return "460";
	case "Skiddo":
		return "672";
	case "Gogoat":
		return "673";
	case "Vulpix":
		return "037";
	case "Ninetales":
		return "038";
	case "Growlithe":
		return "058";
	case "Arcanine":
		return "059";
	case "Ponyta":
		return "077";
	case "Rapidash":
		return "078";
	case "Slugma":
		return "218";
	case "Magcargo":
		return "219";
	case "Numel":
		return "322";
	case "Camerupt":
		return "323";
	case "Darumaka":
		return "554";
	case "Darmanitan":
		return "555";
	case "Litleo":
		return "667";
	case "Pyroar":
		return "668";
	case "Clamperl":
		return "366";
	case "Huntail":
		return "367";
	case "Gorebyss":
		return "368";
	case "Slowpoke":
		return "079";
	case "Slowbro":
		return "080";
	case "Slowking":
		return "199";
	case "Goldeen":
		return "118";
	case "Seaking":
		return "119";
	case "Barboach":
		return "339";
	case "Whiscash":
		return "340";
	case "Finneon":
		return "456";
	case "Lumineon":
		return "457";
	case "Chinchou":
		return "170";
	case "Lanturn":
		return "171";
	case "Carvanha":
		return "318";
	case "Sharpedo":
		return "319";
	case "Wingull":
		return "278";
	case "Pelipper":
		return "279";
	case "Ducklett":
		return "580";
	case "Swanna":
		return "581";
	case "Tentacool":
		return "072";
	case "Tentacruel":
		return "073";
	case "Frillish":
		return "592";
	case "Jellicent":
		return "593";
	case "Shellder":
		return "090";
	case "Cloyster":
		return "091";
	case "Krabby":
		return "098";
	case "Kingler":
		return "099";
	case "Corphish":
		return "341";
	case "Crawdaunt":
		return "342";
	case "Staryu":
		return "120";
	case "Starmie":
		return "121";
	case "Psyduck":
		return "054";
	case "Golduck":
		return "055";
	case "Wooper":
		return "194";
	case "Quagsire":
		return "195";
	case "Seel":
		return "086";
	case "Dewgong":
		return "087";
	case "Shellos":
		return "422";
	case "Gastrodon":
		return "423";
	case "Buizel":
		return "418";
	case "Floatzel":
		return "419";
	case "Remoraid":
		return "223";
	case "Octillery":
		return "224";
	case "Mantyke":
		return "458";
	case "Mantine":
		return "226";
	case "Magikarp":
		return "129";
	case "Gyarados":
		return "130";
	case "Feebas":
		return "349";
	case "Milotic":
		return "350";
	case "Wailmer":
		return "320";
	case "Wailord":
		return "321";
	case "Clauncher":
		return "692";
	case "Clawitzer":
		return "693";
	case "Snorunt":
		return "361";
	case "Glalie":
		return "362";
	case "Froslass":
		return "478";
	case "Cubchoo":
		return "613";
	case "Beartic":
		return "614";
	case "Bergmite":
		return "712";
	case "Avalugg":
		return "713";
	case "Voltorb":
		return "100";
	case "Electrode":
		return "101";
	case "Electrike":
		return "309";
	case "Manectric":
		return "310";
	case "Blitzle":
		return "522";
	case "Zebstrika":
		return "523";
	case "Helioptile":
		return "694";
	case "Heliolisk":
		return "695";
	case "Natu":
		return "177";
	case "Xatu":
		return "178";
	case "Woobat":
		return "527";
	case "Swoobat":
		return "528";
	case "Spoink":
		return "325";
	case "Grumpig":
		return "326";
	case "Munna":
		return "517";
	case "Musharna":
		return "518";
	case "Elgyem":
		return "605";
	case "Beheeyem":
		return "606";
	case "Drowzee":
		return "096";
	case "Hypno":
		return "097";
	case "Smoochum":
		return "238";
	case "Jynx":
		return "124";
	case "Mime Jr.":
		return "439";
	case "Mr. Mime":
		return "122";
	case "Chingling":
		return "433";
	case "Chimecho":
		return "358";
	case "Wynaut":
		return "360";
	case "Wobbuffet":
		return "202";
	case "Espurr":
		return "677";
	case "Meowstic":
		return "678";
	case "Tyrogue":
		return "236";
	case "Hitmonlee":
		return "106";
	case "Hitmonchan":
		return "107";
	case "Hitmontop":
		return "237";
	case "Mankey":
		return "056";
	case "Primeape":
		return "057";
	case "Mienfoo":
		return "619";
	case "Mienshao":
		return "620";
	case "Makuhita":
		return "296";
	case "Hariyama":
		return "297";
	case "Meditite":
		return "307";
	case "Medicham":
		return "308";
	case "Riolu":
		return "447";
	case "Lucario":
		return "448";
	case "Pancham":
		return "674";
	case "Pangoro":
		return "675";
	case "Murkrow":
		return "198";
	case "Honchkrow":
		return "430";
	case "Vullaby":
		return "629";
	case "Mandibuzz":
		return "630";
	case "Purrloin":
		return "509";
	case "Liepard":
		return "510";
	case "Houndour":
		return "228";
	case "Houndoom":
		return "229";
	case "Poochyena":
		return "261";
	case "Mightyena":
		return "262";
	case "Scraggy":
		return "559";
	case "Scrafty":
		return "560";
	case "Sneasel":
		return "215";
	case "Weavile":
		return "461";
	case "Pawniard":
		return "624";
	case "Bisharp":
		return "625";
	case "Zorua":
		return "570";
	case "Zoroark":
		return "571";
	case "Inkay":
		return "686";
	case "Malamar":
		return "687";
	case "Misdreavus":
		return "200";
	case "Mismagius":
		return "429";
	case "Shuppet":
		return "353";
	case "Banette":
		return "354";
	case "Drifloon":
		return "425";
	case "Drifblim":
		return "426";
	case "Yamask":
		return "562";
	case "Cofagrigus":
		return "563";
	case "Phantump":
		return "708";
	case "Trevenant":
		return "709";
	case "Pumpkaboo A":
	case "Pumpkaboo (A)":
	case "Pumpkaboo-A":
	case "Pumpkaboo Average":
	case "Pumpkaboo (Average)":
	case "Pumpkaboo-Average":
		return "710";
	case "Pumpkaboo Sm":
	case "Pumpkaboo (Sm)":
	case "Pumpkaboo-Sm":
	case "Pumpkaboo Small":
	case "Pumpkaboo (Small)":
	case "Pumpkaboo-Small":
		return "710:S";
	case "Pumpkaboo L":
	case "Pumpkaboo (L)":
	case "Pumpkaboo-L":
	case "Pumpkaboo Large":
	case "Pumpkaboo (Large)":
	case "Pumpkaboo-Large":
		return "710:L";
	case "Pumpkaboo Su":
	case "Pumpkaboo (Su)":
	case "Pumpkaboo-Su":
	case "Pumpkaboo Super":
	case "Pumpkaboo (Super)":
	case "Pumpkaboo-Super":
		return "710:SS";
	case "Gourgeist A":
	case "Gourgeist (A)":
	case "Gourgeist-A":
	case "Gourgeist Average":
	case "Gourgeist (Average)":
	case "Gourgeist-Average":
		return "711";
	case "Gourgeist Sm":
	case "Gourgeist (Sm)":
	case "Gourgeist-Sm":
	case "Gourgeist Small":
	case "Gourgeist (Small)":
	case "Gourgeist-Small":
		return "711:S";
	case "Gourgeist L":
	case "Gourgeist (L)":
	case "Gourgeist-L":
	case "Gourgeist Large":
	case "Gourgeist (Large)":
	case "Gourgeist-Large":
		return "711:L";
	case "Gourgeist Su":
	case "Gourgeist (Su)":
	case "Gourgeist-Su":
	case "Gourgeist Super":
	case "Gourgeist (Super)":
	case "Gourgeist-Super":
		return "711:SS";
	case "Spritzee":
		return "682";
	case "Aromatisse":
		return "683";
	case "Swirlix":
		return "684";
	case "Slurpuff":
		return "685";
	case "Pansage":
		return "511";
	case "Simisage":
		return "512";
	case "Pansear":
		return "513";
	case "Simisear":
		return "514";
	case "Panpour":
		return "515";
	case "Simipour":
		return "516";
	case "Farfetch'd":
		return "083";
	case "Chatot":
		return "441";
	case "Dunsparce":
		return "206";
	case "Miltank":
		return "241";
	case "Tauros":
		return "128";
	case "Bouffalant":
		return "626";
	case "Stantler":
		return "234";
	case "Audino":
		return "531";
	case "Spinda":
		return "327";
	case "Kecleon":
		return "352";
	case "Castform":
		return "351";
	case "Smeargle":
		return "235";
	case "Kangaskhan":
		return "115";
	case "Furfrou":
		return "676";
	case "Zangoose":
		return "335";
	case "Seviper":
		return "336";
	case "Shuckle":
		return "213";
	case "Durant":
		return "632";
	case "Pinsir":
		return "127";
	case "Heracross":
		return "214";
	case "Carnivine":
		return "455";
	case "Maractus":
		return "556";
	case "Tropius":
		return "357";
	case "Torkoal":
		return "324";
	case "Heatmor":
		return "631";
	case "Qwilfish":
		return "211";
	case "Basculin":
		return "550";
	case "Relicanth":
		return "369";
	case "Corsola":
		return "222";
	case "Luvdisc":
		return "370";
	case "Alomomola":
		return "594";
	case "Lapras":
		return "131";
	case "Delibird":
		return "225";
	case "Cryogonal":
		return "615";
	case "Pachirisu":
		return "417";
	case "Emolga":
		return "587";
	case "Stunfisk":
		return "618";
	case "Rotom":
	case "Rotom N":
	case "Rotom (N)":
	case "Rotom-N":
	case "Rotom Normal":
	case "Rotom (Normal)":
	case "Rotom-Normal":
		return "479";
	case "Rotom H":
	case "Rotom (H)":
	case "Rotom-H":
	case "Rotom Heat":
	case "Rotom (Heat)":
	case "Rotom-Heat":
		return "479:H";
	case "Rotom W":
	case "Rotom (W)":
	case "Rotom-W":
	case "Rotom Wash":
	case "Rotom (Wash)":
	case "Rotom-Wash":
		return "479:W";
	case "Rotom Fr":
	case "Rotom (Fr)":
	case "Rotom-Fr":
	case "Rotom Frost":
	case "Rotom (Frost)":
	case "Rotom-Frost":
		return "479:Fr";
	case "Rotom Fn":
	case "Rotom (Fn)":
	case "Rotom-Fn":
	case "Rotom Fan":
	case "Rotom (Fan)":
	case "Rotom-Fan":
		return "479:Fa";
	case "Rotom M":
	case "Rotom (M)":
	case "Rotom-M":
	case "Rotom Mow":
	case "Rotom (Mow)":
	case "Rotom-Mow":
		return "479:M";
	case "Dedenne":
		return "702";
	case "Girafarig":
		return "203";
	case "Sigilyph":
		return "561";
	case "Mawile":
		return "303";
	case "Skarmory":
		return "227";
	case "Klefki":
		return "707";
	case "Absol":
		return "359";
	case "Sableye":
		return "302";
	case "Spiritomb":
		return "442";
	case "Druddigon":
		return "621";
	case "Plusle":
		return "311";
	case "Minun":
		return "312";
	case "Volbeat":
		return "313";
	case "Illumise":
		return "314";
	case "Lunatone":
		return "337";
	case "Solrock":
		return "338";
	case "Carbink":
		return "703";
	case "Throh":
		return "538";
	case "Sawk":
		return "539";
	case "Hawlucha":
		return "701";
	case "Ditto":
		return "132";
	case "Unown":
		return "201";
	case "Eevee":
		return "133";
	case "Vaporeon":
		return "134";
	case "Jolteon":
		return "135";
	case "Flareon":
		return "136";
	case "Espeon":
		return "196";
	case "Umbreon":
		return "197";
	case "Leafeon":
		return "470";
	case "Glaceon":
		return "471";
	case "Sylveon":
		return "700";
	case "Omanyte":
		return "138";
	case "Omastar":
		return "139";
	case "Kabuto":
		return "140";
	case "Kabutops":
		return "141";
	case "Lileep":
		return "345";
	case "Cradily":
		return "346";
	case "Anorith":
		return "347";
	case "Armaldo":
		return "348";
	case "Cranidos":
		return "408";
	case "Rampardos":
		return "409";
	case "Shieldon":
		return "410";
	case "Bastiodon":
		return "411";
	case "Tirtouga":
		return "564";
	case "Carracosta":
		return "565";
	case "Archen":
		return "566";
	case "Archeops":
		return "567";
	case "Tyrunt":
		return "696";
	case "Tyrantrum":
		return "697";
	case "Amaura":
		return "698";
	case "Aurorus":
		return "699";
	case "Aerodactyl":
		return "142";
	case "Dratini":
		return "147";
	case "Dragonair":
		return "148";
	case "Dragonite":
		return "149";
	case "Larvitar":
		return "246";
	case "Pupitar":
		return "247";
	case "Tyranitar":
		return "248";
	case "Bagon":
		return "371";
	case "Shelgon":
		return "372";
	case "Salamence":
		return "373";
	case "Beldum":
		return "374";
	case "Metang":
		return "375";
	case "Metagross":
		return "376";
	case "Gible":
		return "443";
	case "Gabite":
		return "444";
	case "Garchomp":
		return "445";
	case "Deino":
		return "633";
	case "Zweilous":
		return "634";
	case "Hydreigon":
		return "635";
	case "Goomy":
		return "704";
	case "Sliggoo":
		return "705";
	case "Goodra":
		return "706";
	case "Mew":
		return "151";
	case "Mewtwo":
		return "150";
	case "Genesect":
		return "649";
	case "Heatran":
		return "485";
	case "Articuno":
		return "144";
	case "Zapdos":
		return "145";
	case "Moltres":
		return "146";
	case "Raikou":
		return "243";
	case "Entei":
		return "244";
	case "Suicune":
		return "245";
	case "Regirock":
		return "377";
	case "Regice":
		return "378";
	case "Registeel":
		return "379";
	case "Regigigas":
		return "486";
	case "Cobalion":
		return "638";
	case "Terrakion":
		return "639";
	case "Virizion":
		return "640";
	case "Keldeo":
		return "647";
	case "Uxie":
		return "480";
	case "Mesprit":
		return "481";
	case "Azelf":
		return "482";
	case "Tornadus I":
	case "Tornadus (I)":
	case "Tornadus-I":
	case "Tornadus Incarnate":
	case "Tornadus (Incarnate)":
	case "Tornadus-Incarnate":
		return "641";
	case "Tornadus T":
	case "Tornadus (T)":
	case "Tornadus-T":
	case "Tornadus Therian":
	case "Tornadus (Therian)":
	case "Tornadus-Therian":
		return "641:T";
	case "Thundurus I":
	case "Thundurus (I)":
	case "Thundurus-I":
	case "Thundurus Incarnate":
	case "Thundurus (Incarnate)":
	case "Thundurus-Incarnate":
		return "642";
	case "Thundurus T":
	case "Thundurus (T)":
	case "Thundurus-T":
	case "Thundurus Therian":
	case "Thundurus (Therian)":
	case "Thundurus-Therian":
		return "642:T";
	case "Landorus I":
	case "Landorus (I)":
	case "Landorus-I":
	case "Landorus Incarnate":
	case "Landorus (Incarnate)":
	case "Landorus-Incarnate":
		return "645";
	case "Landorus T":
	case "Landorus (T)":
	case "Landorus-T":
	case "Landorus Therian":
	case "Landorus (Therian)":
	case "Landorus-Therian":
		return "645:T";
	case "Lugia":
		return "249";
	case "Ho-Oh":
		return "250";
	case "Latias":
		return "380";
	case "Latios":
		return "381";
	case "Phione":
		return "489";
	case "Manaphy":
		return "490";
	case "Celebi":
		return "251";
	case "Jirachi":
		return "385";
	case "Victini":
		return "494";
	case "Shaymin L":
	case "Shaymin (L)":
	case "Shaymin-L":
	case "Shaymin Land":
	case "Shaymin (Land)":
	case "Shaymin-Land":
		return "492";
	case "Shaymin S":
	case "Shaymin (S)":
	case "Shaymin-S":
	case "Shaymin Sky":
	case "Shaymin (Sky)":
	case "Shaymin-Sky":
		return "492:S";
	case "Diancie":
		return "719";
	case "Meloetta A":
	case "Meloetta (A)":
	case "Meloetta-A":
	case "Meloetta Aria":
	case "Meloetta (Aria)":
	case "Meloetta-Aria":
		return "648";
	case "Meloetta S":
	case "Meloetta (S)":
	case "Meloetta-S":
	case "Meloetta Step":
	case "Meloetta (Step)":
	case "Meloetta-Step":
	case "Meloetta P":
	case "Meloetta (P)":
	case "Meloetta-P":
	case "Meloetta Pirouette":
	case "Meloetta (Pirouette)":
	case "Meloetta-Pirouette":
		return "648:S";
	case "Deoxys N":
	case "Deoxys (N)":
	case "Deoxys-N":
	case "Deoxys Normal":
	case "Deoxys (Normal)":
	case "Deoxys-Normal":
		return "386";
	case "Deoxys A":
	case "Deoxys (A)":
	case "Deoxys-A":
	case "Deoxys Attack":
	case "Deoxys (Attack)":
	case "Deoxys-Attack":
		return "386:A";
	case "Deoxys D":
	case "Deoxys (D)":
	case "Deoxys-D":
	case "Deoxys Defense":
	case "Deoxys (Defense)":
	case "Deoxys-Defense":
		return "386:D";
	case "Deoxys S":
	case "Deoxys (S)":
	case "Deoxys-S":
	case "Deoxys Speed":
	case "Deoxys (Speed)":
	case "Deoxys-Speed":
		return "386:S";
	case "Darkrai":
		return "491";
	case "Cresselia":
		return "488";
	case "Kyogre":
		return "382";
	case "Groudon":
		return "383";
	case "Rayquaza":
		return "384";
	case "Reshiram":
		return "643";
	case "Zekrom":
		return "644";
	case "Kyurem":
		return "646";
	case "Kyurem Z":
	case "Kyurem (Z)":
	case "Kyurem-Z":
	case "Kyurem Zekrom":
	case "Kyurem (Zekrom)":
	case "Kyurem-Zekrom":
		return "646:Z";
	case "Kyurem R":
	case "Kyurem (R)":
	case "Kyurem-R":
	case "Kyurem Reshiram":
	case "Kyurem (Reshiram)":
	case "Kyurem-Reshiram":
		return "646:R";
	case "Dialga":
		return "483";
	case "Palkia":
		return "484";
	case "Giratina A":
	case "Giratina (A)":
	case "Giratina-A":
	case "Giratina Altered":
	case "Giratina (Altered)":
	case "Giratina-Altered":
		return "487";
	case "Giratina O":
	case "Giratina (O)":
	case "Giratina-O":
	case "Giratina Origin":
	case "Giratina (Origin)":
	case "Giratina-Origin":
		return "487:O";
	case "Xerneas":
		return "716";
	case "Yveltal":
		return "717";
	case "Zygarde":
		return "718";
	case "Arceus":
		return "493";
	case "Hoopa":
	case "Hoopa C":
	case "Hoopa (C)":
	case "Hoopa-C":
	case "Hoopa Confined":
	case "Hoopa (Confined)":
	case "Hoopa-Confined":
	case "Hoopa B":
	case "Hoopa (B)":
	case "Hoopa-B":
	case "Hoopa Bound":
	case "Hoopa (Bound)":
	case "Hoopa-Bound":
		return "720";
	case "Hoopa U":
	case "Hoopa (U)":
	case "Hoopa-U":
	case "Hoopa Unbound":
	case "Hoopa (Unbound)":
	case "Hoopa-Unbound":
		return "720:U";
}
}